//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db279
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_inf
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public Nullable<int> Age { get; set; }
        public string claddName { get; set; }
    }
}
